version: '3.4'

services:
  cqrs.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  movieservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  catalogservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
