version: '3.4'

services:
  cqrs.gateway:
    image: ${DOCKER_REGISTRY-}cqrsgateway
    container_name: gateway
    ports:
      - "5077:80"
    build:
      context: .
      dockerfile: CQRS.Gateway/Dockerfile
    depends_on:
      - consul

  movieservice:
    image: ${DOCKER_REGISTRY-}movieservice
    container_name: movie_service
    ports:
      #- "6000:443"
      - "6001:80"
    build:
      context: .
      dockerfile: Services/MovieService/Dockerfile
    depends_on:
      - consul

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/
      - ./rabbitmqlogs:/var/log/rabbitmq

  consul:
    image: consul
    container_name: consul
    restart: on-failure
    volumes:
    - consuldata:/consul/config
    ports:
     - "8500:8500"

  postgres:
    container_name: pgdb
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test_db"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mongo:
    container_name: mndb
    image: mongo
    restart: always
    volumes:
        - ./mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    container_name: mongo_admin
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mndb

volumes:
  #elasticsearch-data:
  consuldata:
    name: consul-volume
  mongodbdata:
    name: mongo-database-volume
  pgdata:
    name: postgres-database-volume
  rabbitmqdata:
    name: rabbitmq-data-volue
  rabbitmqlogs:
    name: rabbitmq-logs-volume

